import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
TFLITE_PATH = BASE_DIR / "ml" / "models" / "hero_arise_int8.tflite"
HEADER_PATH = BASE_DIR / "firmware" / "model_data.h"

def convert_tflite_to_c_array():
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    if not TFLITE_PATH.exists():
        print(f"ERROR: Model file missing at {TFLITE_PATH}")
        return False

    with open(TFLITE_PATH, "rb") as f:
        model_bytes = f.read()

    length = len(model_bytes)
    
    lines = []
    lines.append("// Auto-generated by scripts/tflite_to_c_array.py")
    lines.append("// Model: HeroArise_Tiny1DCNN (INT8 TFLite)")
    lines.append("#ifndef MODEL_DATA_H")
    lines.append("#define MODEL_DATA_H")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"// Model binary size: {length} bytes")
    lines.append("alignas(8) const unsigned char hero_arise_model[] = {")

    # Format bytes in hex 12 per line
    hex_bytes = [f"0x{b:02x}" for b in model_bytes]
    for i in range(0, len(hex_bytes), 12):
        chunk = hex_bytes[i:i+12]
        lines.append("  " + ", ".join(chunk) + ",")

    lines.append("};")
    lines.append(f"const unsigned int hero_arise_model_len = {length};")
    lines.append("")
    lines.append("#endif // MODEL_DATA_H")

    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("=" * 50)
    print("EMBEDDED MODEL C-ARRAY GENERATOR")
    print("=" * 50)
    print(f"Input TFLite Model:  {TFLITE_PATH}")
    print(f"Generated Header:    {HEADER_PATH}")
    print(f"Model Length:        {length:,} bytes")
    print("=" * 50)

    return True

if __name__ == "__main__":
    success = convert_tflite_to_c_array()
    if success:
        sys.exit(0)
    else:
        sys.exit(1)
